apiVersion: app/v1
kind: Deployment
metadata:
  name: webapp

spec:
  selector:
    matchLabels:
      app: webapp
  replicas: 1
  template: # template for the pod
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - name: webapp
        image: richardchesterwood/k8s-fleetman-webapp-angular:release0 


