apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
spec:
  selector:
    matchLabels:
      app: api-gateway
  replicas: 2
  template: # template for the pod
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
      - name: api-gateway
        image: richardchesterwood/k8s-fleetman-api-gateway:release1
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: production-microservice 



---

apiVersion: v1
kind: Service
metadata:
  name: fleetman-api-gateway
spec:
  #this define which pods are represented by this service
  selector:
    app: api-gateway

  ports:
    - name : http
      port: 8080


  type: ClusterIP