apiVersion: app/v1
kind: Deployment
metadata:
  name: webapp
spec:
  selector:
    matchLabels:
      app: webapp
  replicas: 1
  template: # template for the pod
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - name: webapp
        image: richardchesterwood/k8s-fleetman-webapp-angular:release1
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: production-microservice 


---

apiVersion: v1
kind: Service
metadata:
  name: fleetman-webapp
  labels: 
    app: webapp
spec:
  #this define which pods are represented by this service
  selector:
    app: webapp
  ports:
    - name : http
      port: 80
  
  type: LoadBalancer