apiVersion: v1
kind: Pod
metadata:
  name: fleetman-mysql
  label:
    app: mysql 
spec:
  containers: # container name and all the components 
    - name: mysql
      image: mysql:5
      env:
        - name: MYSQL_ROOT_PASSWORD
          value: password #this is the password
        - name : MYSQL_DATABASE
          value: fleetman # this is the name of the db
          

---

apiVersion: v1
kind: service
metadata:
  name: database 
spec:
  selector:
    app: mysql 
  ports:
  - port: 3306      
  type: ClusterIP


  #ways to connect to the db from the webapp container 
  # kubectl exec -it webapp sh 
  # apk for alpine : apk update 
  # apk add mysql-client
  # connect to the sql : mysql -h database -uroot -ppassword fleetman 
  